@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDcxMTU1Mjd9.R5H67eiXnjpi9153Lk1qkk-gTakBYYKrj3BpkVUsK8A
@domain = http://localhost:3000

### Users Index
GET {{ domain }}/users
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Users Show
GET {{ domain }}/users/2
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "Jim",
  "last_name": "Bob",
  "tractor_number":
  1428,
  "trailer_number":
  14533,
  "manager": false,
  "location":
  "Granger",
  "email": "astengo03@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "astengo93@gmail.com",
  "password": "password"
}


### User update
PATCH {{ domain }}/users/2
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "first_name": "Ben"
}

### User Destroy
DELETE {{domain}}/users/9
Authorization: Bearer {{ jwt }}

### Customer Index
GET {{ domain }}/customers
Authorization: Bearer {{ jwt }}

### Customer Show
GET {{ domain }}/customers/3
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Customers create (signup)
POST {{ domain }}/customers
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Kwik Star 1068",
  "address": "1704 Broad Street, Story City, Ia 50248"
}

### Orders Index
GET {{ domain }}/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Order create
POST {{ domain }}/orders
Content-Type: application/json
# Authorization: Bearer {{ jwt }}

{
  "customer_id": 3 ,
  "blend": "87 C",
  "volume": 8500,
  "day": "April 29th, 2022",
  "fulfilled": "false",
  "preferred_window": null
}

### Order Update
POST {{ domain }}/orders/1
Content-Type: application/json
# Authorization: Bearer {{ jwt }}

{
  "customer_id": 1,
  "blend": "87 C"
}

### Order Destroy
DELETE {{ domain }}/orders/7?customer_id=4
# Authorization: Bearer {{ jwt }}