@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDY3ODY2MDJ9.AsCnpwj0MV0P1U9xT-b0o4M0j6OQL_CbDdcQSoF2kKo
@domain = http://localhost:3000
### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "first_name": "Ben",
  "last_name": "Astengo",
  "tractor_number":
  1426,
  "trailer_number":
  14531,
  "manager": false,
  "location":
  "Granger",
  "email": "astengo93@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "astengo93@gmail.com",
  "password": "password"
}

### User update
PATCH {{ domain }}/users/2
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "first_name": "Benjamin"
}

### User Destroy
DELETE {{domain}}/users/7
Authorization: Bearer {{ jwt }}

### Customer Index
GET {{ domain }}/customers
Authorization: Bearer {{ jwt }}
### Customers create (signup)
POST {{ domain }}/customers
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Kwik Star 1068",
  "address": "1704 Broad Street, Story City, Ia 50248"
}

### Order create
POST {{ domain }}/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "user_id": 2,
  "customer_id": 3,
  "blend": "87 E",
  "volume": 8500,
  "day": "April 25th, 2022",
  "fulfilled": "false",
  "preferred_window": null
}

### Order Update
POST {{ domain }}/orders/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "blend": "87 C"
}

### Order Destroy
DELETE {{ domain }}/orders/6
Authorization: Bearer {{ jwt }}